### PR TITLE
Task/Use import syntax for treeshaking

### PR DESCRIPTION
**Pull request by jenniferarnesen**
Changes:
* Import syntax for rxjs and recompose from specific modules to enable treeshaking
* remove commented-out code
* remove unused dependencies
* fix eslint issues in translationForm.actions.js
* remove redundant import of d2 getInstance

### CODE REVIEW

**Comment by amcgee** [comment]
(Double checking my **before** build now but I think the increased css size is unrelated)

**Comment by varl** [comment]
I did a double-take on why we need RxJS in core but saw there are more changes in other packages. It's all good, man. :cowboy_hat_face:

**Comment by varl** [comment]
There's a test failure though, related to `Observable.fromPromise` which doesn't exist.

**Comment by jenniferarnesen** [comment]
Test is fixed now (I had forgotten curly braces).  For the umd build of translation-dialog I get this result:

before 1353561
after     1136750

so, 200k smaller.

**Comment by varl** [comment]
# Size comparison

**Before** = master (c739fa7)
**After** = task/enable-treeshaking-d2-ui-core (58a2f60)

```
4.5M    ./packages/app/build (before)
3.3M    ./packages/app/build (after)

5.0M    ./packages/core/build (before)
3.7M    ./packages/core/build (after)

6.2M    ./packages/expression-manager/build (before)
6.2M    ./packages/expression-manager/build (after)

6.8M    ./packages/favorites-dialog/build (before)
5.9M    ./packages/favorites-dialog/build (after)

8.5M    ./packages/favorites-menu/build (before)
7.9M    ./packages/favorites-menu/build (after)

8.7M    ./packages/file-menu/build (before)
8.1M    ./packages/file-menu/build (after)

5.5M    ./packages/forms/build (before)
5.5M    ./packages/forms/build (after)

1.3M    ./packages/formula-editor/build (before)
1.3M    ./packages/formula-editor/build (after)

6.0M    ./packages/group-editor/build (before)
4.7M    ./packages/group-editor/build (after)

1.6M    ./packages/header-bar/build (before)
1.4M    ./packages/header-bar/build (after)

4.6M    ./packages/icon-picker/build (before)
3.3M    ./packages/icon-picker/build (after)

9.4M    ./packages/interpretations/build (before)
8.5M    ./packages/interpretations/build (after)

6.8M    ./packages/legend/build (before)
6.8M    ./packages/legend/build (after)

1.2M    ./packages/mentions-wrapper/build (before)
1.2M    ./packages/mentions-wrapper/build (after)

6.2M    ./packages/org-unit-dialog/build (before)
4.9M    ./packages/org-unit-dialog/build (after)

4.6M    ./packages/org-unit-select/build (before)
3.3M    ./packages/org-unit-select/build (after)

5.3M    ./packages/org-unit-tree/build (before)
4.1M    ./packages/org-unit-tree/build (after)

1.6M    ./packages/period-selector-dialog/build (before)
1.6M    ./packages/period-selector-dialog/build (after)

549K    ./packages/rich-text/build (before)
549K    ./packages/rich-text/build (after)

6.4M    ./packages/sharing-dialog/build (before)
5.6M    ./packages/sharing-dialog/build (after)

4.7M    ./packages/table/build (before)
3.4M    ./packages/table/build (after)

7.4M    ./packages/translation-dialog/build (before)
6.2M    ./packages/translation-dialog/build (after)
```

### cmds
```
rm -rf node_modules
find ./packages -type d -name node_modules | xargs rm -rf
find ./packages -type d -name build | grep -v node_modules | xargs rm -rf

yarn && yarn release

find ./packages -type d -name build | xargs du -hs
```

**Comment by varl** [comment]
# example-app bundle size

```
  663.43 KB (-321.71 KB)  build/static/js/main.a7247263.js
  1.22 KB                 build/static/css/main.7d44b1fb.css
```

**Pull request merged**
