### PR TITLE
DHIS2-5043 - Standardize and clean up dialog styles.

### PR DESCRIPTION
**Pull request by amcgee**
Fixes DHIS2-5043.

Changes proposed in this pull request:

- Override `DialogTitle > h6` component for consistent dialog title styling consistent with design spec
- Standardize the use of `variant="contained"` and `color="primary"` in various `d2-ui` dialog components.
- Remove several cases of custom `style={}` usage
- Use the DHIS2 Mui3 theme in the `d2-ui` create-react-app example.

### CODE REVIEW

**Comment by amcgee** [comment]
Screenshots for easier review @joeDHIS:

screen shot 2018-11-09 at 12 43 54 pm
screen shot 2018-11-09 at 12 44 10 pm
screen shot 2018-11-09 at 12 44 19 pm
screen shot 2018-11-09 at 12 44 26 pm
screen shot 2018-11-09 at 12 44 33 pm
screen shot 2018-11-09 at 12 44 37 pm
screen shot 2018-11-09 at 12 44 42 pm
screen shot 2018-11-09 at 12 44 50 pm
screen shot 2018-11-09 at 12 45 04 pm
screen shot 2018-11-09 at 12 45 13 pm
screen shot 2018-11-09 at 12 45 27 pm

**Comment by amcgee** [comment]
I included all of them for completeness, not just the ones I updated.

@joeDHIS wasn't sure how to deal with the last one (for interpretations, with both "save" and "save & share" primary actions) so I just left it, let me know if you have a better idea (for this change or a later one)

**Comment by joeDHIS** [comment]
@amcgee "Save and share" won't be in the next iteration of the interpretations component (actually, neither will that dialog), so I think we can leave it how it is for now.

**Comment by amcgee** [comment]
@joeDHIS great thanks!

**Pull request merged**
